using IdentityApi.Models;
using Microsoft.EntityFrameworkCore;

namespace IdentityApi.Data
{
    /// <summary>
    /// EF Core database context for the Identity service.
    /// Manages the <c>identity</c> PostgreSQL schema.
    /// Migrations are generated and applied explicitly — never auto-created on startup.
    /// </summary>
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<User>(entity =>
            {
                // PK generated by PostgreSQL
                entity.Property(e => e.Id)
                    .HasDefaultValueSql("gen_random_uuid()");

                // DM-C01: case-insensitive unique index on email.
                // The HasIndex annotation tells EF Core about the index for query/validation
                // purposes. The actual DDL in the migration uses a raw SQL expression index
                // on LOWER(email) so that case-insensitivity is enforced at the database level.
                // Index name per constraint contract: uq_user_email_ci.
                // NOTE: EF Core cannot express functional/expression indexes natively;
                //       the migration overrides the generated index DDL with:
                //         CREATE UNIQUE INDEX uq_user_email_ci ON identity.users (LOWER(email));
                entity.HasIndex(e => e.Email)
                    .IsUnique()
                    .HasDatabaseName("uq_user_email_ci");

                // Server-side UTC defaults for timestamps
                entity.Property(e => e.CreatedAt)
                    .HasDefaultValueSql("timezone('utc', now())");

                entity.Property(e => e.UpdatedAt)
                    .HasDefaultValueSql("timezone('utc', now())");

                // Default active
                entity.Property(e => e.IsActive)
                    .HasDefaultValue(true);
            });

            // NOTE: No HasData() seed here.
            // Seed is managed by DatabaseSeeder (explicit idempotent command).
            // Reason: seeds must be re-runnable without re-running migrations.
            // See SETUP.md "Seed" section.
        }
    }
}
