using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IdentityApi.Models
{
    /// <summary>
    /// Identity service User entity.
    /// Maps to <c>identity.users</c> table.
    /// Owner: Mohamed Tawfik (Identity service).
    /// Release fields: id, team_id, full_name, email, password_hash, role, is_active, timestamps.
    /// See wiki: Data Model ERD — August 24 Release ERD / USER entity.
    /// </summary>
    [Table("users", Schema = "identity")]
    public class User
    {
        /// <summary>PK — generated by PostgreSQL gen_random_uuid().</summary>
        [Key]
        [Column("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Release scope key. Must match the seeded Project.team_id (DM-C06).
        /// Temporary release simplification; replaced by TeamMember model post-Aug-24.
        /// </summary>
        [Column("team_id")]
        public Guid TeamId { get; set; }

        /// <summary>Display name — ERD field: full_name.</summary>
        [Required]
        [MaxLength(255)]
        [Column("full_name")]
        public required string FullName { get; set; }

        /// <summary>
        /// Unique email address (case-insensitive, enforced by uq_user_email_ci index — DM-C01).
        /// </summary>
        [Required]
        [MaxLength(255)]
        [Column("email")]
        public required string Email { get; set; }

        /// <summary>BCrypt-hashed password (cost 11). Never store plaintext.</summary>
        [Required]
        [Column("password_hash")]
        public required string PasswordHash { get; set; }

        /// <summary>
        /// Release role value: "Lead".
        /// Full Role/TeamMember permission model is deferred post-Aug-24.
        /// </summary>
        [Required]
        [MaxLength(50)]
        [Column("role")]
        public required string Role { get; set; }

        /// <summary>Whether the account is active. Defaults to true.</summary>
        [Column("is_active")]
        public bool IsActive { get; set; } = true;

        /// <summary>Record creation timestamp (UTC).</summary>
        [Column("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>Record last-updated timestamp (UTC).</summary>
        [Column("updated_at")]
        public DateTime UpdatedAt { get; set; }
    }
}
